$engine: 3
$onesync: on
name: Feather
description: The official recipe for Feather Framework.
version: 1.0.0
author: bcc

tasks:
  # Prepare Database
  - action: connect_database

  # Download DB
  - action: download_github
    url: https://github.com/FeatherFramework/feather-recipe
    path: ./temp/feather-recipe

  # Migrate(Setup) Database Tables
  - action: query_database
    file: ./temp/feather-recipe/database/migration.sql

  # Seed Database
  - action: query_database
    file: ./temp/feather-recipe/database/seed.sql

  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources

  # Move the server config over
  - action: move_path
    src: ./temp/feather-recipe/server.cfg
    dest: ./server.cfg

  # Move the server icon over 
  - action: move_path
    src: ./temp/feather-recipe/servericon.png
    dest: ./servericon.png

  # Download Feather files
  - action: download_github
    url: https://github.com/FeatherFramework/feather-core
    ref: main
    path: ./resources/[feather]

  # Clean up db files
  - action: remove_path
    path: ./temp
